### ISSUE TITLE
Issue when testing on windows

### ISSUE THREAD

**Issue by smawais90** [pixielabs/cavy#148]
Issue only occurs when testing on windows. It's working fine on mac. We need to run it on a windows pc.

$ cavy run-android
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
cavy: Running `react-native run-android`...
cavy: Putting your index.js back.
cavy: Running `mv index.js index.test.js && mv index.notest.js index.js`...
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: spawn react-native ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn react-native',
  path: 'react-native',
  spawnargs: [ 'run-android', 'run-android' ]
}

**Comment by AbigailMcP** [comment]
Hi @smawais90 ! Thanks for reporting this issue, the problem was with cavy-cli and I've just [rolled out a fix](https://github.com/pixielabs/cavy-cli/pull/21) in version 1.3.2.

Let me know if you still have the same problem after upgrading.
