### ISSUE TITLE
Can't see test outputs in expo project

### ISSUE THREAD

**Issue by sabbir0179** [pixielabs/cavy#195]
After running cavy run-ios --skipbuild in a react-native project using expo, I'm getting the following lines in console:

```
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
cavy: Listening on port 8082 for test results...
```
The app is already running in a simulator but I don't see any test output in neither expo metro bundler nor the terminal console. Any suggestions on how to solve this issue and see my test results?

**Comment by AbigailMcP** [comment]
Hmm interesting - can you visually see your app progressing through your test scenarios in the simulator or not? If not, this would suggest the tests aren't running at all and Cavy isn't correctly set up in your test app.

This might be a silly question, but after Cavy reported `cavy: Listening on port 8082 for test results...` did you refresh your app? The app will need to refresh after `index.test.js` is swapped in. The tests should then run.

If they still don't, can you build your app manually using `index.test.js` and does that work?

**Comment by hoshinaoshi** [comment]
@AbigailMcP 
I have the same problem.

## Prerequisite information

```
$ node -v 
v12.18.1

$ expo -V
3.24.0

$ cavy -V
1.1.0
```

## execution procedure

```
$ expo init cavyTest
? Choose a template: (Use arrow keys)
  ----- Managed workflow -----
❯ blank                 a minimal app as clean as an empty canvas 
  blank (TypeScript)    same as blank but with TypeScript configuration 
  tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript 
  ----- Bare workflow -----
  minimal               bare and minimal, just the essentials to get you started 
  minimal (TypeScript)  same as minimal but with TypeScript configuration 

$ cd cavyTest/
$ yarn add cavy --dev

$ cavy init
cavy: Adding Cavy to your project...
cavy: Done!
```

## modify index.test.js

```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Tester, TestHookStore } from 'cavy';
import ExampleSpec from './specs/exampleSpec';
import App from './App';

const testHookStore = new TestHookStore();

class AppWrapper extends Component {
  render() {
    return (
      <Tester specs={[ExampleSpec]} store={testHookStore}>
        <App />
      </Tester>
    );
  }
}

AppRegistry.registerComponent('yourAppName', () => AppWrapper);
```

## execution result
```
$ cavy run-ios --skipbuild
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
mv: rename index.js to index.notest.js: No such file or directory
child_process.js:669
    throw err;
    ^

Error: Command failed: mv index.js index.notest.js && mv index.test.js index.js
mv: rename index.js to index.notest.js: No such file or directory

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at switchEntryFile (/Users/naoshi_hoshi/.config/yarn/global/node_modules/cavy-cli/src/runTests.js:25:3)
    at runTests (/Users/naoshi_hoshi/.config/yarn/global/node_modules/cavy-cli/src/runTests.js:121:5)
    at test (/Users/naoshi_hoshi/.config/yarn/global/node_modules/cavy-cli/cavy.js:37:3)
    at Command.<anonymous> (/Users/naoshi_hoshi/.config/yarn/global/node_modules/cavy-cli/cavy.js:68:18)
    at Command.listener (/Users/naoshi_hoshi/.config/yarn/global/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Users/naoshi_hoshi/.config/yarn/global/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/naoshi_hoshi/.config/yarn/global/node_modules/commander/index.js:474:21) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6d 76 3a 20 72 65 6e 61 6d 65 20 69 6e 64 65 78 2e 6a 73 20 74 6f 20 69 6e 64 65 78 2e 6e 6f 74 65 73 74 2e 6a 73 3a 20 4e 6f 20 73 75 63 68 20 66 69 ... 16 more bytes>
  ],
  pid: 13959,
  stdout: <Buffer >,
  stderr: <Buffer 6d 76 3a 20 72 65 6e 61 6d 65 20 69 6e 64 65 78 2e 6a 73 20 74 6f 20 69 6e 64 65 78 2e 6e 6f 74 65 73 74 2e 6a 73 3a 20 4e 6f 20 73 75 63 68 20 66 69 ... 16 more bytes>
}


$ cp index.test.js index.js 

$ cavy run-ios --skipbuild
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
cavy: Listening on port 8082 for test results...
```

and, I open http://localhost:8082  in my browser but it continues to load forever.

Is there anything else I should do?

**Comment by AbigailMcP** [comment]
Solved in https://github.com/pixielabs/cavy-cli/issues/34
