### ISSUE TITLE
Problems with running it on Wndows

### ISSUE THREAD

**Issue by creotiv** [pixielabs/cavy#196]
> cavy run-android --skipbuild
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
'mv' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:669
    throw err;
    ^

Error: Command failed: mv index.js index.notest.js && mv index.test.js index.js
'mv' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at switchEntryFile (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\src\runTests.js:25:3)
    at runTests (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\src\runTests.js:121:5)
    at test (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\cavy.js:37:3)
    at Command.<anonymous> (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\cavy.js:86:18)
    at Command.listener (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\creot\AppData\Roaming\npm\node_modules\cavy-cli\node_modules\commander\index.js:474:21) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 6d 76 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 6c 20 ... 43 more bytes>
  ],
  pid: 23760,
  stdout: <Buffer >,
  stderr: <Buffer 27 6d 76 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 6c 20 ... 43 more bytes>
}

**Comment by jalada** [comment]
Whoops! Thanks @creotiv, we don't test frequently on Windows, not surprised this slipped through the net.

**Comment by creotiv** [comment]
Added small patch for that https://github.com/pixielabs/cavy-cli/pull/35

**Comment by AbigailMcP** [comment]
Fixed in https://github.com/pixielabs/cavy-cli/pull/39
