### ISSUE TITLE
Importing Cavy breaks Jest tests that use react-test-renderer

### ISSUE THREAD

**Issue by Kynosaur** [pixielabs/cavy#42]
Hi, myself and my group used Cavy for one of our projects, and we loved it apart from this one thing - we were all super new to React Native and had under two weeks to learn the framework and make an app, which is why I've not made a pull request for this straight away (I'm not sure how hacky it is, or if there's a more elegant solution, it worked for us so we moved on), but hopefully this helps somewhat.

Problem
-

Given a simple test like the one below (or any test that renders components like this):

```
it('renders correctly', () => {
  const tree = renderer.create(
    <SearchBar />
  );
});
```

We get the following error/stack trace:

```
TypeError: Cannot read property 'add' of undefined

      at node_modules/cavy/src/hook.js:60:25
      at commitAttachRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5545:1)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6262:1)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2180:6)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2127:25)
      at commitAllWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6376:1)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6649:1)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2180:6)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2127:25)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6764:1)
```

Solution
-

We threw in a quick fix which simply involved making the generateTestHook() method (within node_modules/cavy/src/hook.js) return early if 'this.context.testHooks' ('this' being some sort of wrapper, we didn't have time to learn more about that object) wasn't defined:

`if(!this.context.testHooks) { return }`

So the whole method looks like:

```
generateTestHook(identifier, f = () => {}) {
      return (component) => {
        if(!this.context.testHooks) { return }
        if (component) {
          this.context.testHooks.add(identifier, component);
        } else {
          this.context.testHooks.remove(identifier, component);
        }
        f(component);
      }
    }
```

**Comment by jalada** [comment]
Hi @Kynosaur! If I'm honest, returning early after checking to see if `testHooks` is available feels like the _correct_ approach.

However you should also still call `f(component)`, that's the passed in test hook generating function which the user may be using.

If you set up a PR with that in place, we can test it and get it in the next release 🎉

**Comment by Kynosaur** [comment]
Thank you @jalada! PR created 👍
